#!/bin/sh
# Verify a weaverssh binary distribution archive and optional detached signature.
set -eu
LC_ALL=C
LANG=C
export LC_ALL LANG

usage() {
  cat <<'USAGE'
usage: verify_binary_distribution.sh --archive FILE [options]

Options:
  --archive FILE        Binary distribution .tar.gz archive to verify.
  --checksum FILE       SHA-256 sidecar. Default: <archive>.sha256 when present.
  --signature FILE      OpenSSL detached signature generated by --sign-key.
  --public-key FILE     OpenSSL public key for --signature verification.
  --gpg-signature FILE  GPG detached signature generated by --sign/--gpg-key.
  --extract-dir DIR     Directory used for extraction. Default: temporary dir.
  --smoke               Run extracted scripts/smoke-test.sh after checksum checks.
  -h, --help            Show this help.
USAGE
}

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

archive=
checksum=
signature=
public_key=
gpg_signature=
extract_dir=
smoke=false
cleanup=true

while [ "$#" -gt 0 ]; do
  case "$1" in
    --archive) archive=${2:?missing --archive value}; shift 2 ;;
    --checksum) checksum=${2:?missing --checksum value}; shift 2 ;;
    --signature) signature=${2:?missing --signature value}; shift 2 ;;
    --public-key) public_key=${2:?missing --public-key value}; shift 2 ;;
    --gpg-signature) gpg_signature=${2:?missing --gpg-signature value}; shift 2 ;;
    --extract-dir) extract_dir=${2:?missing --extract-dir value}; cleanup=false; shift 2 ;;
    --smoke) smoke=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1" ;;
  esac
done

[ -n "$archive" ] || { usage; exit 2; }
[ -f "$archive" ] || die "archive not found: $archive"
if [ -z "$checksum" ] && [ -f "$archive.sha256" ]; then
  checksum="$archive.sha256"
fi

sha_file() {
  if have openssl; then
    openssl dgst -sha256 -r "$1" | awk '{print $1}'
  elif have sha256sum; then
    sha256sum "$1" | awk '{print $1}'
  elif have shasum; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    die "need openssl, sha256sum, or shasum"
  fi
}

if [ -n "$checksum" ]; then
  [ -f "$checksum" ] || die "checksum file not found: $checksum"
  expected=$(awk '{print $1; exit}' "$checksum")
  actual=$(sha_file "$archive")
  [ "$expected" = "$actual" ] || die "archive checksum mismatch: expected $expected got $actual"
  printf 'archive checksum: ok\n'
else
  printf 'archive checksum: skipped (no sidecar provided)\n'
fi

if [ -n "$signature" ]; then
  [ -n "$public_key" ] || die "--public-key is required with --signature"
  [ -f "$signature" ] || die "signature not found: $signature"
  [ -f "$public_key" ] || die "public key not found: $public_key"
  have openssl || die "openssl is required for signature verification"
  openssl dgst -sha256 -verify "$public_key" -signature "$signature" "$archive" >/dev/null
  printf 'openssl signature: ok\n'
elif [ -n "$gpg_signature" ]; then
  [ -f "$gpg_signature" ] || die "gpg signature not found: $gpg_signature"
  have gpg || die "gpg is required for GPG signature verification"
  gpg --verify "$gpg_signature" "$archive" >/dev/null
  printf 'gpg signature: ok\n'
else
  printf 'signature: skipped\n'
fi

if [ -z "$extract_dir" ]; then
  extract_dir=$(mktemp -d "${TMPDIR:-/tmp}/weaverssh-verify.XXXXXX")
fi
if [ "$cleanup" = "true" ]; then
  trap 'rm -rf "$extract_dir"' EXIT
fi
mkdir -p "$extract_dir"
tar -xzf "$archive" -C "$extract_dir"
root=$(find "$extract_dir" -mindepth 1 -maxdepth 1 -type d | LC_ALL=C sort | head -1)
[ -n "$root" ] || die "archive did not contain a top-level directory"
[ -f "$root/CHECKSUMS.txt" ] || die "missing CHECKSUMS.txt"

while read -r expected rel rest; do
  [ -n "$expected" ] || continue
  [ -z "$rest" ] || die "unsupported checksum path with spaces: $rel $rest"
  [ -f "$root/$rel" ] || die "missing checksummed file: $rel"
  actual=$(sha_file "$root/$rel")
  [ "$expected" = "$actual" ] || die "internal checksum mismatch for $rel: expected $expected got $actual"
done < "$root/CHECKSUMS.txt"
printf 'internal checksums: ok\n'

[ -f "$root/MANIFEST.json" ] || die "missing MANIFEST.json"
[ -f "$root/SECURITY.json" ] || die "missing SECURITY.json"
printf 'manifest: %s\n' "$root/MANIFEST.json"
printf 'security: %s\n' "$root/SECURITY.json"

if [ "$smoke" = "true" ]; then
  [ -x "$root/scripts/smoke-test.sh" ] || die "missing executable smoke test"
  "$root/scripts/smoke-test.sh"
fi

printf 'verify: ok\n'
