package vfs

import "testing"

func TestDetectWSL(t *testing.T) {
	cases := map[string]bool{
		"5.15.153.1-microsoft-standard-WSL2\n": true,
		"4.4.0-19041-Microsoft\n":              true, // WSL1
		"6.6.0-generic\n":                      false,
		"Linux version 5.15.0 (Ubuntu)":        false,
	}
	for in, want := range cases {
		if got := detectWSL(in); got != want {
			t.Errorf("detectWSL(%q)=%v want %v", in, got, want)
		}
	}
}

func TestParseResolvNameserver(t *testing.T) {
	content := "# generated by WSL\nnameserver 172.20.16.1\nnameserver fe80::1\n"
	if got := parseResolvNameserver(content); got != "172.20.16.1" {
		t.Errorf("parseResolvNameserver=%q want 172.20.16.1", got)
	}
	if got := parseResolvNameserver("search lan\n"); got != "" {
		t.Errorf("parseResolvNameserver(no ns)=%q want empty", got)
	}
}

func TestParseDefaultGatewayProcRoute(t *testing.T) {
	// Gateway 0x0110A8C0 little-endian = 192.168.16.1; default row Destination 00000000.
	content := "Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\n" +
		"eth0\t0010A8C0\t00000000\t0001\t0\t0\t0\t00FFFFFF\n" +
		"eth0\t00000000\t0110A8C0\t0003\t0\t0\t0\t00000000\n"
	if got := parseDefaultGatewayProcRoute(content); got != "192.168.16.1" {
		t.Errorf("parseDefaultGatewayProcRoute=%q want 192.168.16.1", got)
	}
	// No default route present.
	none := "Iface\tDestination\tGateway\n eth0\t0010A8C0\t00000000\n"
	if got := parseDefaultGatewayProcRoute(none); got != "" {
		t.Errorf("parseDefaultGatewayProcRoute(no default)=%q want empty", got)
	}
}

func TestResolveSentinel(t *testing.T) {
	// Non-sentinel hosts are untouched.
	for _, addr := range []string{"127.0.0.1:5640", "10.0.0.5:9999", "example.com:5640"} {
		if got := resolveSentinel(addr); got != addr {
			t.Errorf("resolveSentinel(%q)=%q want unchanged", addr, got)
		}
	}
	// Sentinels resolve to a concrete host:port (Windows host IP, or loopback
	// fallback). Either way the port is preserved and the host is not a sentinel.
	for _, addr := range []string{"windows-host:5640", "wsl-host:1080", "WINDOWS-HOST:5640"} {
		got := resolveSentinel(addr)
		if got == addr {
			t.Errorf("resolveSentinel(%q) did not resolve", addr)
		}
		if want := ":5640"; addr == "windows-host:5640" && got[len(got)-5:] != want {
			t.Errorf("resolveSentinel(%q)=%q lost port", addr, got)
		}
	}
}

func TestIsSentinel(t *testing.T) {
	if !isSentinel("windows-host") || !isSentinel("WSL-Host") {
		t.Error("expected sentinels to match (case-insensitive)")
	}
	if isSentinel("127.0.0.1") || isSentinel("host") {
		t.Error("non-sentinel matched")
	}
}
