#!/usr/bin/env python3
from __future__ import annotations

"""Generate VS Code extension-host env profiles for SSHX11 routing modes."""

import argparse
import json
from pathlib import Path
import shutil
import time
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_DIR = REPO_ROOT / ".vscode" / "sshx11"
DEFAULT_MCP_TEMPLATE = REPO_ROOT / "tools" / "verification" / "mcp.vscode.example.json"
DEFAULT_MCP_OUTPUT = REPO_ROOT / ".vscode" / "mcp.json"


def _resolve_path(value: str | Path) -> Path:
    p = Path(value).expanduser()
    if p.is_absolute():
        return p
    return (REPO_ROOT / p).resolve()


def _render_profile(
    *,
    profile: str,
    local_proxy_uri: str,
    reverse_proxy_uri: str,
    no_proxy: str,
) -> str:
    lines: list[str] = [
        "#!/usr/bin/env sh",
        "# Generated by tools/verification/generate_sshx11_vscode_profile.py",
    ]
    if profile == "local":
        lines.extend(
            [
                "# Profile: local extension host routed through local SOCKS fallback.",
                "export SSHX11_VSCODE_PROFILE=local",
                f'export ALL_PROXY="{local_proxy_uri}"',
                'export HTTP_PROXY="$ALL_PROXY"',
                'export HTTPS_PROXY="$ALL_PROXY"',
                f'export NO_PROXY="{no_proxy}"',
            ]
        )
    elif profile == "remote":
        lines.extend(
            [
                "# Profile: remote extension host without explicit proxy (direct egress path).",
                "export SSHX11_VSCODE_PROFILE=remote",
                "unset ALL_PROXY",
                "unset HTTP_PROXY",
                "unset HTTPS_PROXY",
                f'export NO_PROXY="{no_proxy}"',
            ]
        )
    elif profile == "reverse-socks":
        lines.extend(
            [
                "# Profile: remote extension host routed through reverse SOCKS listener.",
                "export SSHX11_VSCODE_PROFILE=reverse-socks",
                f'export ALL_PROXY="{reverse_proxy_uri}"',
                'export HTTP_PROXY="$ALL_PROXY"',
                'export HTTPS_PROXY="$ALL_PROXY"',
                f'export NO_PROXY="{no_proxy}"',
            ]
        )
    else:
        raise ValueError(f"unsupported profile: {profile}")
    lines.append("")
    return "\n".join(lines)


def _write_profile(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    try:
        mode = path.stat().st_mode
        path.chmod(mode | 0o111)
    except Exception:
        pass


def run_generation(args: argparse.Namespace) -> dict[str, Any]:
    profile = str(args.profile).strip().lower()
    requested = ["local", "remote", "reverse-socks"] if profile == "all" else [profile]

    output_dir = _resolve_path(args.output_dir)
    local_proxy_uri = f"socks5h://{args.local_socks_host}:{int(args.local_socks_port)}"
    reverse_proxy_uri = f"socks5h://{args.reverse_socks_host}:{int(args.reverse_socks_port)}"
    no_proxy = str(args.no_proxy).strip() or "127.0.0.1,localhost"

    generated: dict[str, str] = {}
    for name in requested:
        content = _render_profile(
            profile=name,
            local_proxy_uri=local_proxy_uri,
            reverse_proxy_uri=reverse_proxy_uri,
            no_proxy=no_proxy,
        )
        path = output_dir / f"{name}.env.sh"
        _write_profile(path, content)
        generated[name] = str(path)

    mcp_written = False
    mcp_result = ""
    if bool(args.write_mcp):
        template = _resolve_path(args.mcp_template)
        output = _resolve_path(args.mcp_output)
        if output.exists() and not bool(args.overwrite_mcp):
            mcp_result = "skipped_existing"
        else:
            output.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(template, output)
            mcp_written = True
            mcp_result = "written"
    else:
        mcp_result = "disabled"

    source_hints = {
        name: f". {path}"
        for name, path in generated.items()
    }
    return {
        "ok": True,
        "timestamp_unix": int(time.time()),
        "profile_request": profile,
        "output_dir": str(output_dir),
        "generated_profiles": generated,
        "proxy_uris": {
            "local": local_proxy_uri,
            "reverse_socks": reverse_proxy_uri,
            "no_proxy": no_proxy,
        },
        "source_hints": source_hints,
        "mcp": {
            "write_enabled": bool(args.write_mcp),
            "result": mcp_result,
            "written": mcp_written,
            "template": str(_resolve_path(args.mcp_template)),
            "output": str(_resolve_path(args.mcp_output)),
        },
    }


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--profile", choices=["local", "remote", "reverse-socks", "all"], default="all")
    p.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    p.add_argument("--local-socks-host", default="127.0.0.1")
    p.add_argument("--local-socks-port", type=int, default=1080)
    p.add_argument("--reverse-socks-host", default="127.0.0.1")
    p.add_argument("--reverse-socks-port", type=int, default=19080)
    p.add_argument("--no-proxy", default="127.0.0.1,localhost")
    p.add_argument("--write-mcp", action="store_true", default=True, help="Write .vscode/mcp.json from template.")
    p.add_argument("--no-write-mcp", action="store_false", dest="write_mcp")
    p.add_argument("--mcp-template", type=Path, default=DEFAULT_MCP_TEMPLATE)
    p.add_argument("--mcp-output", type=Path, default=DEFAULT_MCP_OUTPUT)
    p.add_argument("--overwrite-mcp", action="store_true", default=False)
    return p


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)
    payload = run_generation(args)
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
